### ISSUE TITLE
Append Builder: Error seldon-core-microservice not found; Default image not correct

### ISSUE THREAD

**Issue by jlewi** [kubeflow/fairing#196]
I tried building a deploying an endpoint

```
fairing.config.set_deployer('serving', serving_class="LabelPrediction")
create_endpoint = fairing.config.fn(LabelPrediction)
create_endpoint()
```

The deployed pod ended up crashing with the following error.

```
kubectl logs fairing-deployer-9mkf8-57c554f979-c572d
container_linux.go:247: starting container process caused "exec: \"seldon-core-microservice\": executable file not found in $PATH"
```

Container spec is

```
spec:
  containers:
  - command:
    - seldon-core-microservice
    - LabelPrediction
    - REST
    - --service-type=MODEL
    - --persistence=0
    env:
    - name: FAIRING_RUNTIME
      value: "1"
    image: gcr.io/code-search-demo/fairing-job:BEF9445D
    imagePullPolicy: IfNotPresent
    name: model
    resources: {}
    securityContext:
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-rqqln
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: gke-label-issues-040-label-issues-040-cf06394a-t02q
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-rqqln
    secret:
      defaultMode: 420
      secretName: default-token-rqqln
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2019-04-10T03:43:37Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2019-04-10T03:43:37Z
    message: 'containers with unready status: [model]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    message: 'containers with unready status: [model]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: 2019-04-10T03:43:37Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://dbe925a3d4fe386348ee5b6b4a2e533e3cf449af51af9335afe1298b5e9c656f
    image: gcr.io/code-search-demo/fairing-job:BEF9445D
    imageID: docker-pullable://gcr.io/code-search-demo/fairing-job@sha256:ddea06ddd16c92f80d9e14bf5e1c126635eedefdbe23c52067724c7430807262
    lastState:
      terminated:
        containerID: docker://dbe925a3d4fe386348ee5b6b4a2e533e3cf449af51af9335afe1298b5e9c656f
        exitCode: 127
        finishedAt: 2019-04-10T03:51:23Z
        message: |
          oci runtime error: container_linux.go:247: starting container process caused "exec: \"seldon-core-microservice\": executable file not found in $PATH"
        reason: ContainerCannotRun
        startedAt: 2019-04-10T03:51:23Z
    name: model
    ready: false
    restartCount: 6
    state:
      waiting:
        message: Back-off 5m0s restarting failed container=model pod=fairing-deployer-9mkf8-57c554f979-c572d_kubeflow(d2ee14f0-5b42-11e9-aa05-42010a8e0051)
        reason: CrashLoopBackOff
  hostIP: 10.142.0.10
  phase: Running
  podIP: 10.0.0.29
  qosClass: BestEffort
  startTime: 2019-04-10T03:43:37Z
```
